# Generated by Django 4.0.5 on 2022-06-20 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompraChocolate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initial_amount', models.PositiveIntegerField()),
                ('cost_chocolate_bar', models.PositiveIntegerField()),
                ('wrappers_free', models.PositiveIntegerField()),
                ('chocolate_eaten', models.IntegerField()),
            ],
        ),
    ]
