# Generated by Django 4.0.5 on 2022-06-21 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comprachocolate',
            name='chocolate_eaten',
            field=models.IntegerField(default=0),
        ),
    ]
